[tools]
bat = "0.26.1"
cmake = "4.3.1"
delta = "latest"
fd = "10.4.2"
fzf = "0.71.0"
lazydocker = "0.25.0"
lazygit = "0.61.1"
lua = "5.5.0"
neovim = "0.12.1"
node = "25.6.1"
ripgrep = "15.1.0"
starship = "1.24.2"
tmux = "3.6a"
tree-sitter = "0.26.8"
yazi = "26.1.22"

# Bootstrap will install all necessary dependencies
# Execute: mise run bootstrap
[tasks.bootstrap]
run = """
npm install -g @mermaid-js/mermaid-cli
"""
