[tools]
bat = "0.26.1"
cmake = "4.3.1"
delta = "latest"
fd = "10.4.2"
fzf = "0.71.0"
herdr = "latest"
jq = "latest"
lazydocker = "0.25.0"
lazygit = "0.61.1"
lua = "5.5.0"
neovim = "0.12.1"
node = "lts"
ripgrep = "15.1.0"
starship = "1.24.2"
tmux = "3.6a"
tombi = "latest"
tree-sitter = "0.26.8"
uv = "latest"
yazi = "26.1.22"

[dotfiles]
"~/.config/starship.toml" = "~/dotfiles/starship.toml"
"~/.config/mise" = "~/dotfiles/mise"
"~/.config/zsh" = "~/dotfiles/zsh"
"~/.config/aerospace" = "~/dotfiles/aerospace"
"~/.config/ag" = "~/dotfiles/ag"
"~/.config/clangd" = "~/dotfiles/clangd"
"~/.config/cursor" = "~/dotfiles/cursor"
"~/.config/fish" = "~/dotfiles/fish"
"~/.config/ghostty" = "~/dotfiles/ghostty"
"~/.config/herdr" = "~/dotfiles/herdr"
"~/.config/kanata" = "~/dotfiles/kanata"
"~/.config/karabiner" = "~/dotfiles/karabiner"
"~/.config/nvim" = "~/dotfiles/nvim"
"~/.config/tmux" = "~/dotfiles/tmux"
"~/.config/yazi" = "~/dotfiles/yazi"

# Bootstrap will install all necessary dependencies
# Execute: mise run bootstrap
[tasks.bootstrap]
run = """
npm install -g @mermaid-js/mermaid-cli
curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
"""

# Install utils for embedded development
# Execute: mise run embedded
[tasks.embedded]
run = """
cargo-binstall hexyl binsider
"""

[shell_alias]
# applies the configured herdr layout
herdr-layout = "herdr plugin action invoke herdr-spreader.apply"
ll = "ls -lh"
la = "ls -ah"
lla = "ls -lah"
tree = "tree -L 2 "
kb = "$HOME/.kanata.sh"

[settings]
experimental = true
dotfiles.default_mode = "symlink"
dotfiles.root = "~/dotfiles"
